name: Update Credly Badges

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-badges:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - title: Checkout Repository
        uses: actions/checkout@v4

      - title: Update Badges
        uses: erichalldev/credly-badges-readme-action@main
        with:
          credly_user: nilo-lima-jr
          badge_count: 83 # Aqui você define quantas quer mostrar (ex: as 10 mais recentes)
